# CDDB options
CDDBMETHOD=cddb
CDDBURL="http://gnudb.gnudb.org/~cddb/cddb.cgi"
CDDBCOPYLOCAL="y"
CDDBLOCALDIR="$HOME/.cddb"
CDDBLOCALRECURSIVE="y"
CDDBUSELOCAL="y"

# Encoders
MP3ENCODERSYNTAX=lame
LAME=lame
LAMEOPTS="-V 0 -h --silent"

FLACENCODERSYNTAX=flac
FLAC=flac
FLACOPTS="-s -e -V -5"

# CD reader program
# CDROMREADERSYNTAX=libcdio
CD_PARANOIA=cd-paranoia
CDPARANOIAOPTS="-O 6 --never-skip=40"

# Tagging
CDDISCID=cd-discid
ID3TAGV=id3v2.3

# Actions to take
ACTIONS=cddb,read,playlist,encode,tag,move,clean
OUTPUTTYPE="mp3,flac"

# Where to save?
OUTPUTDIR="$HOME/Music/ripped"
OUTPUTFORMAT='${OUTPUT}/${ARTISTFILE}-${ALBUMFILE}-${YEAR}-${OUTPUT}/${TRACKNUM}-${ARTISTFILE}-${TRACKFILE}'
VAOUTPUTFORMAT='${OUTPUT}/VA-${ALBUMFILE}-${YEAR}-${OUTPUT}/${TRACKNUM}-${ARTISTFILE}-${TRACKFILE}'
PLAYLISTFORMAT='${OUTPUT}/${ARTISTFILE}-${ALBUMFILE}-${YEAR}-${OUTPUT}/00-${ARTISTFILE}-${ALBUMFILE}-${YEAR}.m3u'
VAPLAYLISTFORMAT='${OUTPUT}/VA-${ALBUMFILE}-${YEAR}-${OUTPUT}/00-va-${ALBUMFILE}-${YEAR}.m3u'

# Custom filename munging:
# Translate everything to lowercase
# replace ALL chars that may cause trouble for Linux, Windows and DOS
# with '_' (underscore); remove double underscores; remove leading and
# trailing underscores; recode to flat ASCII. WARNING! You'll likely
# need to install "recode" on your system as an extra package to use
# this.
mungefilename ()
{
    echo "$@" | \
            sed "s/[- ,.:\'\/!@#\?\$%\^&]/_/g" | \
            sed 's/_[_]*/_/g' | \
            sed 's/^_*//' | \
            sed 's/_*$//' | \
            recode -f iso8859-1..flat
}

# Extra options
PADTRACKS=y
EXTRAVERBOSE=2
MAXPROCS=2
LOWDISK=n
EJECTCD=y
