# NOTE: fileSystems for /, /nix, /boot, and /persist are generated by disko
# from the mountpoints in disko.nix, so they are not declared here.
# Check den.provides.disko-btrfs-impermanence-main to get an idea.
{inputs, ...}: {
  flake-file.inputs.impermanence = {
    url = "github:nix-community/impermanence";
    inputs.nixpkgs.follows = "";
    inputs.home-manager.follows = "";
  };

  den.aspects.impermanence = {user, ...}: {
    nixos = {utils, ...}: {
      imports = [inputs.impermanence.nixosModules.impermanence];

      # Wipe root subvolume on boot, keeping old snapshots for 30 days
      boot.initrd.systemd = {
        enable = true; # Default in 26.05
        services.wipe-file-systems = {
          # Specify dependencies explicitly
          unitConfig.DefaultDependencies = false;
          # The script needs to run to completion before this service is done
          serviceConfig.Type = "oneshot";
          # This service is required for boot to succeed
          requiredBy = ["initrd.target"];
          # Should complete before any file systems are mounted
          before = ["sysroot.mount"];

          # Wait for the disk to appear (partlabel comes from disko: disk-<disk>-<part>)
          requires = ["${utils.escapeSystemdPath "/dev/disk/by-partlabel/disk-main-root"}.device"];
          after = [
            "${utils.escapeSystemdPath "/dev/disk/by-partlabel/disk-main-root"}.device"
            # Allow hibernation to resume before trying to alter any data
            "local-fs-pre.target"
          ];

          script = ''
            set -euo pipefail

            mkdir /btrfs_tmp
            mount /dev/disk/by-partlabel/disk-main-root /btrfs_tmp
            mkdir -p /btrfs_tmp/old_roots

            if [[ -e /btrfs_tmp/root ]]; then
                timestamp=$(date --date="@$(stat -c %Y /btrfs_tmp/root)" "+%Y-%m-%d_%H:%M:%S")
                mv -T /btrfs_tmp/root "/btrfs_tmp/old_roots/$timestamp"
            fi

            # Pruning old snapshots is best-effort: a single failed deletion
            # must not block the new root from being created and boot from
            # succeeding.
            for i in $(find /btrfs_tmp/old_roots/ -mindepth 1 -maxdepth 1 -mtime +30); do
                btrfs subvolume delete --recursive "$i" || echo "warning: failed to delete $i" >&2
            done

            btrfs subvolume create /btrfs_tmp/root
            umount /btrfs_tmp
          '';
        };
      };
    };

    # Default stuff that we want to persist on host/user basis
    impermanence = {
      hideMounts = true;
      directories = [
        "/var/lib/nixos"
        "/var/lib/systemd/coredump"
        "/var/lib/systemd/timers"
        "/var/log"
      ];
      files = [
        "/etc/machine-id"
      ];
      # XDG user folders are persisted by the aspect that creates them
      # (see steve/xdg-folders.nix); only account-baseline entries live here.
      users.${user.name} = {
        directories = [
          "Projects"
          {
            directory = ".ssh";
            mode = "0700";
          }
        ];
        files = [];
      };
    };
  };
}
